### ISSUE TITLE
Minimal version - Not seem to work on QGIS 3.0.1 - Metadata.txt

### ISSUE THREAD

**Issue by ERHash** [geograndest/qgis-plugin#6]
Hi,

thank you for your plugin

the script dont work on qgis 3.0.1 (PyQGIS 3.6)

Could be a problem with the module QgsNetworkReplyContent, Its listed in PyQGIS 3.6 [https://qgis.org/pyqgis/3.6/](https://qgis.org/pyqgis/3.6/) but maybe the module have changed a bit
```
from qgis.core import QgsNetworkReplyContent
Traceback (most recent call last):
  File "H:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
ImportError: cannot import name 'QgsNetworkReplyContent'
```

So I think the minimal version of QGIS is higher

Then I suggest to change the metadata.txt about the minimal version (currently is 3.0.0)
